export const data = {
    banners: [
        {img: '/assets/banners/banner-1.png', link: '/categories/camisa/camisa-css'},
        {img: '/assets/banners/banner-2.png', link: '/categories/camisa/camisa-laravel'},
        {img: '/assets/banners/banner-3.png', link: '/categories/camisa/camisa-nodejs'},
        {img: '/assets/banners/banner-4.png', link: '/categories/camisa/camisa-php'},
    ],
    products: [
        {
            id: 1,
            label: 'Camisa PHP',
            slug: 'camisa-php',
            category: 'camisa',
            description: 'Camiseta PHP de alta qualidade, feita com algodão premium. Perfeita para desenvolvedores que amam a linguagem mais popular da web. Design exclusivo com estampa durável e confortável para o dia a dia.',
            img: '/assets/products/camiseta-php.png',
            images: [
                '/assets/products/camiseta-php.png',
                '/assets/products/camiseta-php-grafite.png',
            ],
            price: 29.90,
            priceOriginal: 49.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG'],
            colors: [
                { name: 'Roxo', hex: '#7B68AE' },
                { name: 'Grafite', hex: '#4A4A4A' },
            ],
            details: [
                '100% Algodão Penteado',
                'Estampa em Silk Screen de Alta Durabilidade',
                'Modelagem Regular Fit',
                'Gola Ribana Reforçada',
                'Costura Dupla nas Mangas e Barra',
            ],
        },
        {
            id: 2,
            label: 'Camisa Laravel',
            slug: 'camisa-laravel',
            category: 'camisa',
            description: 'Camiseta Laravel exclusiva para fãs do framework PHP mais elegante do mundo. Tecido macio e resistente, ideal para meetups, conferências e o dia a dia do desenvolvedor.',
            img: '/assets/products/camiseta-laravel-branca.png',
            images: [
                '/assets/products/camiseta-laravel-branca.png',
                '/assets/products/camiseta-laravel-azul.png',
                '/assets/products/camiseta-laravel-preta.png',
                '/assets/products/camiseta-Laravel-cinza.png',
            ],
            price: 39.90,
            priceOriginal: 59.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG', 'XG'],
            colors: [
                { name: 'Branca', hex: '#FFFFFF' },
                { name: 'Azul', hex: '#3B82F6' },
                { name: 'Preta', hex: '#1A1A1A' },
                { name: 'Cinza', hex: '#9CA3AF' },
            ],
            details: [
                '100% Algodão Penteado 30.1',
                'Estampa Silk Screen Premium',
                'Modelagem Regular Fit',
                'Gola Ribana com Elastano',
                'Lavagem Pré-Encolhimento',
            ],
        },
        {
            id: 3,
            label: 'Camisa ReactJS',
            slug: 'camisa-reactjs',
            category: 'camisa',
            description: 'Camiseta ReactJS com design moderno e cores vibrantes. Feita para quem respira componentes e hooks. Material premium com caimento perfeito.',
            img: '/assets/products/camiseta-react-azul.png',
            images: [
                '/assets/products/camiseta-react-azul.png',
                '/assets/products/camiseta-react-cinza.png',
                '/assets/products/camiseta-react-preta.png',
                '/assets/products/camiseta-react-native.png',
            ],
            price: 39.90,
            priceOriginal: 59.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG'],
            colors: [
                { name: 'Azul', hex: '#61DAFB' },
                { name: 'Cinza', hex: '#6B7280' },
                { name: 'Preta', hex: '#1A1A1A' },
                { name: 'Escura', hex: '#282C34' },
            ],
            details: [
                '100% Algodão Premium',
                'Estampa Digital de Alta Resolução',
                'Modelagem Slim Fit',
                'Gola Careca Reforçada',
                'Acabamento Premium nas Costuras',
            ],
        },
        {
            id: 4,
            label: 'Camisa Javascript',
            slug: 'camisa-javascript',
            category: 'camisa',
            description: 'Camiseta Javascript estilosa para os amantes da linguagem que roda em todo lugar. Estampa vibrante do logo JS com acabamento impecável.',
            img: '/assets/products/camiseta-js.png',
            images: [
                '/assets/products/camiseta-js.png',
                '/assets/products/camiseta-node.png',
                '/assets/products/camiseta-node-preta.png',
            ],
            price: 29.90,
            priceOriginal: 44.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG', 'XG'],
            colors: [
                { name: 'Amarela', hex: '#F7DF1E' },
                { name: 'Verde', hex: '#68A063' },
                { name: 'Preta', hex: '#1A1A1A' },
            ],
            details: [
                '100% Algodão Egípcio',
                'Estampa Silk Screen Importada',
                'Modelagem Regular Fit',
                'Gola Ribana com Elastano',
                'Tingimento Ecológico',
            ],
        },
        {
            id: 5,
            label: 'Camisa CSS',
            slug: 'camisa-css',
            category: 'camisa',
            description: 'Camiseta CSS para quem faz a web ficar bonita. Design criativo com o logo CSS3 em estampa de alta qualidade.',
            img: '/assets/products/camiseta-css.png',
            images: [
                '/assets/products/camiseta-css.png',
                '/assets/products/camiseta-html.png',
            ],
            price: 29.90,
            priceOriginal: 44.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG'],
            colors: [
                { name: 'Azul', hex: '#264DE4' },
                { name: 'Laranja', hex: '#E44D26' },
            ],
            details: [
                '100% Algodão Penteado',
                'Estampa Sublimação de Alta Fidelidade',
                'Modelagem Regular Fit',
                'Gola Ribana Reforçada',
                'Costura Industrial Reforçada',
            ],
        },
        {
            id: 6,
            label: 'Boné B7 Azul',
            slug: 'bone-b7-azul',
            category: 'bone',
            description: 'Boné B7 Azul com aba reta e fechamento snapback. Perfeito para complementar seu look dev com estilo.',
            img: '/assets/products/bone-b7-azul.png',
            images: [
                '/assets/products/bone-b7-azul.png',
                '/assets/products/bone-b7-azul-claro.png',
            ],
            price: 49.90,
            priceOriginal: 69.90,
            liked: false,
            sizes: ['Único'],
            colors: [
                { name: 'Azul', hex: '#1E3A5F' },
                { name: 'Azul Claro', hex: '#87CEEB' },
            ],
            details: [
                'Material: Algodão e Poliéster',
                'Aba Reta com Estrutura',
                'Fechamento Snapback Ajustável',
                'Bordado Frontal de Alta Qualidade',
                'Forro Interno em Mesh',
            ],
        },
        {
            id: 7,
            label: 'Boné B7 Preto',
            slug: 'bone-b7-preto',
            category: 'bone',
            description: 'Boné B7 Preto clássico e versátil. Design minimalista com bordado premium. O acessório perfeito para qualquer ocasião.',
            img: '/assets/products/bone-b7-preto.png',
            images: [
                '/assets/products/bone-b7-preto.png',
                '/assets/products/bone-b7-preto2.png',
                '/assets/products/bone-b7-cinza.png',
                '/assets/products/bone-b7-branco.png',
            ],
            price: 49.90,
            priceOriginal: 69.90,
            liked: false,
            sizes: ['Único'],
            colors: [
                { name: 'Preto', hex: '#1A1A1A' },
                { name: 'Preto Alt', hex: '#2D2D2D' },
                { name: 'Cinza', hex: '#808080' },
                { name: 'Branco', hex: '#F5F5F5' },
            ],
            details: [
                'Material: Algodão Premium',
                'Aba Reta Estruturada',
                'Fechamento Snapback Regulável',
                'Bordado 3D Frontal',
                'Forro Interno Respirável',
            ],
        },
        {
            id: 8,
            label: 'Camisa Node.js',
            slug: 'camisa-nodejs',
            category: 'camisa',
            description: 'Camiseta Node.js para quem vive no mundo do backend JavaScript. Estampa exclusiva com o logo do Node.js em alta definição. Tecido leve e respirável, perfeito para maratonas de código e eventos tech.',
            img: '/assets/products/camiseta-node.png',
            images: [
                '/assets/products/camiseta-node.png',
                '/assets/products/camiseta-node-preta.png',
            ],
            price: 34.90,
            priceOriginal: 54.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG', 'XG'],
            colors: [
                { name: 'Verde', hex: '#68A063' },
                { name: 'Preta', hex: '#1A1A1A' },
            ],
            details: [
                '100% Algodão Penteado 30.1',
                'Estampa Silk Screen de Alta Durabilidade',
                'Modelagem Regular Fit',
                'Gola Ribana com Elastano',
                'Tingimento Ecológico Certificado',
            ],
        },
        {
            id: 9,
            label: 'Calça Jogger JavaScript',
            slug: 'calca-jogger-javascript',
            category: 'calca',
            description: 'Calça jogger com tema JavaScript, feita para quem quer conforto total na rotina de código com estilo tech.',
            img: '/assets/products/camiseta-js.png',
            images: [
                '/assets/products/camiseta-js.png',
                '/assets/products/camiseta-node-preta.png',
            ],
            price: 89.90,
            priceOriginal: 119.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG'],
            colors: [
                { name: 'Preta', hex: '#1A1A1A' },
                { name: 'Amarela', hex: '#F7DF1E' },
            ],
            details: [
                'Tecido Moletinho com Elastano',
                'Modelagem Jogger Unissex',
                'Cós com Ajuste em Cordão',
                'Estampa Tech de Alta Durabilidade',
                'Bolsos Laterais Funcionais',
            ],
        },
        {
            id: 10,
            label: 'Calça Cargo DevOps',
            slug: 'calca-cargo-devops',
            category: 'calca',
            description: 'Calça cargo inspirada em DevOps, com visual urbano e bolsos extras para o dia a dia no escritório ou home office.',
            img: '/assets/products/camiseta-node.png',
            images: [
                '/assets/products/camiseta-node.png',
                '/assets/products/camiseta-node-preta.png',
            ],
            price: 99.90,
            priceOriginal: 139.90,
            liked: false,
            sizes: ['M', 'G', 'GG', 'XG'],
            colors: [
                { name: 'Verde', hex: '#68A063' },
                { name: 'Grafite', hex: '#4A4A4A' },
            ],
            details: [
                'Sarja Premium com Toque Macio',
                'Modelagem Cargo Moderna',
                'Bolsos Utilitários com Fecho',
                'Acabamento Reforçado nas Costuras',
                'Caimento Confortável para Uso Diário',
            ],
        },
        {
            id: 11,
            label: 'Moletom React Hooks',
            slug: 'moletom-react-hooks',
            category: 'moletom',
            description: 'Moletom React Hooks para quem vive de componentes. Interior flanelado e estampa exclusiva com visual minimalista.',
            img: '/assets/products/camiseta-react-preta.png',
            images: [
                '/assets/products/camiseta-react-preta.png',
                '/assets/products/camiseta-react-cinza.png',
            ],
            price: 129.90,
            priceOriginal: 169.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG'],
            colors: [
                { name: 'Preto', hex: '#1A1A1A' },
                { name: 'Cinza', hex: '#6B7280' },
            ],
            details: [
                'Moletom 3 Cabos Premium',
                'Interior Flanelado',
                'Capuz Ajustável com Cordão',
                'Bolso Canguru Frontal',
                'Estampa DTF de Alta Resistência',
            ],
        },
        {
            id: 12,
            label: 'Moletom Python AI',
            slug: 'moletom-python-ai',
            category: 'moletom',
            description: 'Moletom com tema Python e IA para devs que gostam de conforto sem abrir mão do estilo.',
            img: '/assets/products/camiseta-php.png',
            images: [
                '/assets/products/camiseta-php.png',
                '/assets/products/camiseta-php-grafite.png',
            ],
            price: 134.90,
            priceOriginal: 179.90,
            liked: false,
            sizes: ['M', 'G', 'GG', 'XG'],
            colors: [
                { name: 'Roxo', hex: '#7B68AE' },
                { name: 'Grafite', hex: '#4A4A4A' },
            ],
            details: [
                'Moletom Felpado Internamente',
                'Punhos e Barra Canelados',
                'Modelagem Unissex Relaxed Fit',
                'Capuz Duplo com Forro',
                'Estampa Durável para Uso Frequente',
            ],
        },
        {
            id: 13,
            label: 'Bermuda Code Sprint',
            slug: 'bermuda-code-sprint',
            category: 'bermuda',
            description: 'Bermuda casual para maratonas de código, com visual tech e tecido leve para dias quentes.',
            img: '/assets/products/camiseta-css.png',
            images: [
                '/assets/products/camiseta-css.png',
                '/assets/products/camiseta-html.png',
            ],
            price: 79.90,
            priceOriginal: 99.90,
            liked: false,
            sizes: ['P', 'M', 'G', 'GG'],
            colors: [
                { name: 'Azul', hex: '#264DE4' },
                { name: 'Laranja', hex: '#E44D26' },
            ],
            details: [
                'Tecido Leve de Secagem Rápida',
                'Cós Elástico com Ajuste',
                'Modelagem Regular',
                'Bolsos Frontais Funcionais',
                'Estampa Tech de Alta Definição',
            ],
        },
        {
            id: 14,
            label: 'Bermuda Full Stack',
            slug: 'bermuda-full-stack',
            category: 'bermuda',
            description: 'Bermuda full stack com design moderno para quem curte conforto e produtividade em qualquer ambiente.',
            img: '/assets/products/camiseta-laravel-preta.png',
            images: [
                '/assets/products/camiseta-laravel-preta.png',
                '/assets/products/camiseta-laravel-azul.png',
            ],
            price: 84.90,
            priceOriginal: 109.90,
            liked: false,
            sizes: ['M', 'G', 'GG', 'XG'],
            colors: [
                { name: 'Preta', hex: '#1A1A1A' },
                { name: 'Azul', hex: '#3B82F6' },
            ],
            details: [
                'Malha Premium Respirável',
                'Acabamento Reforçado',
                'Modelagem Confort Fit',
                'Bolsos Laterais e Traseiro',
                'Ideal para Uso Diário',
            ],
        },
    ],
}